---

unitClasses:
  - id: mana_crystal
    name: structure_name_mana_crystal
    movement: land_building
    aiPriority: 3.0
    cargoSpace: 1
    battleUnitCount: 1
    damageMultiplier: 1
    isStructure: true
    canReinforce: false
    canBeReinforced: false
    canBeCaptured: true
    isNeutraliseable: true
    income: 0
    cost: 500
    regeneration: 10
    tags:
      - structure
    sightRange: 1


units:
  - class: mana_crystal
    faction: neutral
    name: structure_name_mana_crystal
    mapAnimation: units/mana_crystal/map_mana_crystal_cherrystone
    smallPortrait: units/commanders/emeric/portrait_crystal_small.png
    mediumPortrait: units/commanders/emeric/portrait_crystal_medium.png
    grabPos: [13, 14]
    sounds:
      death: emeric/emericCrystalDie
      deathMap: unitDie
      deathMapNoBattle: emeric/emericCrystalDie
      hit: hitStone
      hitMap: hitStone
    structureImage:
      spriteSheet: backgrounds/city/city_background_full
      farBackground: city_background_full_background_2
      nearBackground: city_background_full_background_1
      foreground: city_background_full_foreground
      keeperPosition: [78, 95]
      leftBannerOffset: [-6, 2]
      rightBannerOffset: [0, 2]

...
