---

# This is the string configuration file for English.
en-GB:
  # New Archer
  unit_class_name_new_archer: "New Archer"
  unit_description_new_archer: "Ranged ground units able to move and attack in the same turn. Critical hit when stationary. Same as old archer basically."
  unit_name_new_archer_cherrystone: "New Ranger"
  unit_name_new_archer_felheim: "New Dreadbow"
  unit_name_new_archer_heavensong: "New Hawkbow"
  unit_name_new_archer_floran: "New Shooter"

  # Mana Crystal
  structure_name_mana_crystal: "Mana Crystal"
  unit_description_mana_crystal: "A crystal which increases the owner's mana by 1"

  # Unused Mana Indicator
  structure_name_mana_indicator: "Mana Crystal"
  unit_description_mana_indicatorl: "A crystal which increases the owner's mana by 1"
  groove_name_indicate_mana: "None"
  groove_description_indicate_mana: "None"

  # Triggers
  trigger_action_name_set_state: "Set State"                                                                            # The name
  trigger_action_description_set_state: "Sets the unit state."                                                          # The general description
  trigger_action_readable_set_state: Add set state {3} to {4} for unit type(s) {0} at location {1} owned by player {2}. # Numbers are filled in by user choices.

  trigger_condition_name_state: "Has State"                                                                                   # The name
  trigger_condition_description_state: "Triggers if a unit has a particular state."                                           # The general description
  trigger_condition_readable_state: "If unit type(s) {0} at location {1} owned by player {2} have state {3} equal to {4}."    # Numbers are filled in by user choices.

  # Verbs
  ui_unit_verbs_swim_under: Swim Under
  ui_unit_verbs_free_turn: Free Move

  groove_name_diplomacy: Diplomacy
  
  # CODEX
  # Overhealing
  codex_projectgroove_overheal: "Overheal"
  codex_rules_projectgroove_overheal_title: "Overhealing\n(Project Groove mod)"
  codex_rules_projectgroove_overheal_text_1: "Overhealing is a system of giving units above 100% health through some abilities. Overhealed units have the following attributes:\n> Healing will not restore their health above 100%.\n> Damage dealt increases proportional to their health."
  codex_rules_projectgroove_overheal_text_2: "> Defence is restricted to the effects of 100% health.\n> Commanders will immediately return to 100% health on the start of their next turn.\n> Overhealed units will display a flashing Heart icon."
  
  # Mana
  codex_projectgroove_mana: "Mana"
  codex_rules_projectgroove_mana_title: "Mana\n(Project Groove mod)"
  codex_rules_projectgroove_mana_text_1: "Mana is a unique resource generated by Mana Crystals, a special building type. It is used for Spells and Recruiting certain units. This includes the following:\n> Spells: Heal, Hex\n> Units: Mage, Giant, Sky Rider, Dragon."
  codex_rules_projectgroove_mana_text_2: "Remaining Mana is displayed as Groove on ally Strongholds. Mana has the following attributes:\n> Mana Crystals provide 1 Mana at the start of each turn.\n> All remaining Mana will be lost at the end of the turn, and cannot be spent."

  # Random Damage Variance
  codex_projectgroove_rng: "Random Damage"
  codex_rules_projectgroove_rng_title: "Random Damage Variance\n(Project Groove mod)"
  codex_rules_projectgroove_rng_text_1: "In Project Groove, damage variance is modified.\nA unit's attack will be modified by a random amount by up to ±5 or ±10% of the average damage, whichever is smaller.\nExamples:\n> 40 avg. results in 36 - 44.\n> 90 avg. results in 85 - 95."
  codex_rules_projectgroove_rng_text_2: "Like before, final damage values are rounded from decimal values.\nExample:\n> 34 avg. results in 31.6 - 38.4, giving a range of 32 - 38."

  # CODEX / UNITS
  # Thief
  unit_description_thief: "A vulnerable unit that can steal 300 gold from enemy buildings, 1000 from a Stronghold, or take over a transport!"
  codex_unit_thief_critical_text: "Thieves are able to instantly neutralise structures, and as such, excel at threatening dangerous areas of the battlefield alone. They are often at their most effective when diverting attention away from the frontlines, and when used effectively, they can turn the economic tide of battle. Additionally, thieves can take over enemy transports, working as a detterent to potential supply lines or the use of cheap blockades."
  
  # Barge
  unit_description_travelboat: "Boats able to transport all ground units across water. Able to move twice when empty."
  codex_unit_travelboat_critical_text: "The Barge is primarily used to transport ground units across sea tiles. Care must be taken, as Barges are vulnerable, and loaded units will be lost if the boat is defeated. However, with its extremely mobile speed when unoccupied, they make effective blockades. A Barge can also move towards a beach before units load onto it, allowing for rapid transportation with only a single vehicle."

  # Turtle
  unit_description_turtle: "Powerful naval unit, built to conquer the water. Half movement after waiting. Critical hit when in deep sea."
  
  # CODEX / COMMANDERS
  codex_groove_description_caesar: "Caesar's majestic presence inspires all adjacent units to dig deep and have a second go.\n\nGroove Charge Speed: Slow."
  codex_groove_description_mercia: "Mercia raises her sword to the sky and heals all surrounding allied units by 50%, overhealing all units up to 105%\n\nGroove Charge Speed: Fast."
  codex_groove_description_nuru: "Nuru beams down a friendly unit in the heat of battle. You can only summon units normally found as a squadron (e.g. Dogs) and can currently recruit. You pay double gold for the unit, but no Mana.\n\nGroove Charge Speed: Medium."
  codex_groove_description_ryota: "Ryota dashes through rows of enemies, dealing 50% of the damage he would inflict at full health. The damage decreases by 3% per row. Ryota can dash through neutral structures.\n\nGroove Charge Speed: Fast."
  codex_groove_description_sigrid: "Sigrid flies up to 2 tiles away, before draining all health from an enemy unit, and adds it to her own health. \n\nGroove Charge Speed: Medium."
  codex_groove_description_twins: "The twins have access to two successive Grooves: Scorching Fire and Cooling Water. \nFirst, you use Scorching Fire, starting a fire on a single tile. For three turns, the flaming area grows in size, and after four turns, it disappears. Any unit caught in the flames will be instantly defeated. \nAfterwards, you may optionally also use Cooling Water, covering an area with healing magic. Each turn, the area decreases in size, and after four turns it disappears. Any units left in the area at the start of the twins' turn are healed for 20% of their full health. \n\nGroove Charge Speed: Medium."
  codex_groove_description_vesper: "Vesper can warp to anywhere on the map and summon a small shroud around her in thick, magical smoke for one turn. Units within this area cannot be targeted or counter-attacked. \n\nGroove Charge Speed: Slow."
  codex_groove_description_darkmercia: "Dark Mercia raises her sword to the sky and drains all surrounding enemy units by 25%, healing herself, and overhealing up to 200%. \n\nGroove Charge Speed: Medium."
  codex_groove_description_mercival: "Mercival diplomatically claims any enemy building to join his side at full strength, and steals 100 gold from the enemy. Cannot be used on Strongholds. \n\nGroove Charge Speed: Fast."
  codex_groove_description_elodie": "Requiem entrances an enemy unit, bringing it under Elodie's control. \n\nGroove charge speed: Medium."
...
